### PR TITLE
add `main` to package.json

### PR DESCRIPTION
**Pull request by shuvalov-anton**
add `main` to `package.json` to correct `require('respond.js')` with `browserify` from `node_modules`

### CODE REVIEW

**Comment by igl** [comment]
:+1: But I would actually point it to `dest/respond.src.js` like in the bowser.json.
Tools like browserify and webpack should have access to the uncompressed source.

**Comment by shuvalov-anton** [comment]
:+1:

**Comment by igl** [comment]
@shuvalov-anton Care to update your pr-diff? :)

**Comment by shuvalov-anton** [comment]
@igl why? [This project](https://github.com/scottjehl/Respond/graphs/commit-activity) is dead. Isn't?

**Pull request closed without merging**
